(asdf:operate 'asdf:load-op 'ae2zot)
(use-package
    :trio-utils)

(defvar num-areas 15)
(defvar areas (loop for i from 1 to num-areas collect i))
(defconstant bin-area 13)
(defconstant tombstone 14)
(defconstant conveyor-belt 15)

(define-var adjacent *int* *int* *bool*)
(defconstant grid-adjacency 
  (alw (&& (!! (-P- adjacent 1 1)) 
      (-P- adjacent 1 2) 
      (!! (-P- adjacent 1 3)) 
      (!! (-P- adjacent 1 4)) 
      (-P- adjacent 1 5) 
      (-P- adjacent 1 6) 
      (!! (-P- adjacent 1 7)) 
      (!! (-P- adjacent 1 8)) 
      (!! (-P- adjacent 1 9)) 
      (!! (-P- adjacent 1 10)) 
      (!! (-P- adjacent 1 11)) 
      (!! (-P- adjacent 1 12)) 
      (!! (-P- adjacent 1 13)) 
      (-P- adjacent 1 14) 
      (!! (-P- adjacent 1 15)) 
      (-P- adjacent 2 1) 
      (!! (-P- adjacent 2 2)) 
      (-P- adjacent 2 3) 
      (!! (-P- adjacent 2 4)) 
      (-P- adjacent 2 5) 
      (-P- adjacent 2 6) 
      (-P- adjacent 2 7) 
      (!! (-P- adjacent 2 8)) 
      (!! (-P- adjacent 2 9)) 
      (!! (-P- adjacent 2 10)) 
      (!! (-P- adjacent 2 11)) 
      (!! (-P- adjacent 2 12)) 
      (!! (-P- adjacent 2 13)) 
      (-P- adjacent 2 14) 
      (!! (-P- adjacent 2 15)) 
      (!! (-P- adjacent 3 1)) 
      (-P- adjacent 3 2) 
      (!! (-P- adjacent 3 3)) 
      (-P- adjacent 3 4) 
      (!! (-P- adjacent 3 5)) 
      (-P- adjacent 3 6) 
      (-P- adjacent 3 7) 
      (-P- adjacent 3 8) 
      (!! (-P- adjacent 3 9)) 
      (!! (-P- adjacent 3 10)) 
      (!! (-P- adjacent 3 11)) 
      (!! (-P- adjacent 3 12)) 
      (!! (-P- adjacent 3 13)) 
      (!! (-P- adjacent 3 14)) 
      (-P- adjacent 3 15) 
      (!! (-P- adjacent 4 1)) 
      (!! (-P- adjacent 4 2)) 
      (-P- adjacent 4 3) 
      (!! (-P- adjacent 4 4)) 
      (!! (-P- adjacent 4 5)) 
      (!! (-P- adjacent 4 6)) 
      (-P- adjacent 4 7) 
      (-P- adjacent 4 8) 
      (!! (-P- adjacent 4 9)) 
      (!! (-P- adjacent 4 10)) 
      (!! (-P- adjacent 4 11)) 
      (!! (-P- adjacent 4 12)) 
      (!! (-P- adjacent 4 13)) 
      (!! (-P- adjacent 4 14)) 
      (-P- adjacent 4 15) 
      (-P- adjacent 5 1) 
      (-P- adjacent 5 2) 
      (!! (-P- adjacent 5 3)) 
      (!! (-P- adjacent 5 4)) 
      (!! (-P- adjacent 5 5)) 
      (-P- adjacent 5 6) 
      (!! (-P- adjacent 5 7)) 
      (!! (-P- adjacent 5 8)) 
      (-P- adjacent 5 9) 
      (-P- adjacent 5 10) 
      (!! (-P- adjacent 5 11)) 
      (!! (-P- adjacent 5 12)) 
      (!! (-P- adjacent 5 13)) 
      (!! (-P- adjacent 5 14)) 
      (!! (-P- adjacent 5 15)) 
      (-P- adjacent 6 1) 
      (-P- adjacent 6 2) 
      (-P- adjacent 6 3) 
      (!! (-P- adjacent 6 4)) 
      (-P- adjacent 6 5) 
      (!! (-P- adjacent 6 6)) 
      (-P- adjacent 6 7) 
      (!! (-P- adjacent 6 8)) 
      (-P- adjacent 6 9) 
      (-P- adjacent 6 10) 
      (-P- adjacent 6 11) 
      (!! (-P- adjacent 6 12)) 
      (!! (-P- adjacent 6 13)) 
      (!! (-P- adjacent 6 14)) 
      (!! (-P- adjacent 6 15)) 
      (!! (-P- adjacent 7 1)) 
      (-P- adjacent 7 2) 
      (-P- adjacent 7 3) 
      (-P- adjacent 7 4) 
      (!! (-P- adjacent 7 5)) 
      (-P- adjacent 7 6) 
      (!! (-P- adjacent 7 7)) 
      (-P- adjacent 7 8) 
      (!! (-P- adjacent 7 9)) 
      (-P- adjacent 7 10) 
      (-P- adjacent 7 11) 
      (-P- adjacent 7 12) 
      (!! (-P- adjacent 7 13)) 
      (!! (-P- adjacent 7 14)) 
      (!! (-P- adjacent 7 15)) 
      (!! (-P- adjacent 8 1)) 
      (!! (-P- adjacent 8 2)) 
      (-P- adjacent 8 3) 
      (-P- adjacent 8 4) 
      (!! (-P- adjacent 8 5)) 
      (!! (-P- adjacent 8 6)) 
      (-P- adjacent 8 7) 
      (!! (-P- adjacent 8 8)) 
      (!! (-P- adjacent 8 9)) 
      (!! (-P- adjacent 8 10)) 
      (-P- adjacent 8 11) 
      (-P- adjacent 8 12) 
      (!! (-P- adjacent 8 13)) 
      (!! (-P- adjacent 8 14)) 
      (!! (-P- adjacent 8 15)) 
      (!! (-P- adjacent 9 1)) 
      (!! (-P- adjacent 9 2)) 
      (!! (-P- adjacent 9 3)) 
      (!! (-P- adjacent 9 4)) 
      (-P- adjacent 9 5) 
      (-P- adjacent 9 6) 
      (!! (-P- adjacent 9 7)) 
      (!! (-P- adjacent 9 8)) 
      (!! (-P- adjacent 9 9)) 
      (-P- adjacent 9 10) 
      (!! (-P- adjacent 9 11)) 
      (!! (-P- adjacent 9 12)) 
      (!! (-P- adjacent 9 13)) 
      (!! (-P- adjacent 9 14)) 
      (!! (-P- adjacent 9 15)) 
      (!! (-P- adjacent 10 1)) 
      (!! (-P- adjacent 10 2)) 
      (!! (-P- adjacent 10 3)) 
      (!! (-P- adjacent 10 4)) 
      (-P- adjacent 10 5) 
      (-P- adjacent 10 6) 
      (-P- adjacent 10 7) 
      (!! (-P- adjacent 10 8)) 
      (-P- adjacent 10 9) 
      (!! (-P- adjacent 10 10)) 
      (-P- adjacent 10 11) 
      (!! (-P- adjacent 10 12)) 
      (!! (-P- adjacent 10 13)) 
      (!! (-P- adjacent 10 14)) 
      (!! (-P- adjacent 10 15)) 
      (!! (-P- adjacent 11 1)) 
      (!! (-P- adjacent 11 2)) 
      (!! (-P- adjacent 11 3)) 
      (!! (-P- adjacent 11 4)) 
      (!! (-P- adjacent 11 5)) 
      (-P- adjacent 11 6) 
      (-P- adjacent 11 7) 
      (-P- adjacent 11 8) 
      (!! (-P- adjacent 11 9)) 
      (-P- adjacent 11 10) 
      (!! (-P- adjacent 11 11)) 
      (-P- adjacent 11 12) 
      (-P- adjacent 11 13) 
      (!! (-P- adjacent 11 14)) 
      (!! (-P- adjacent 11 15)) 
      (!! (-P- adjacent 12 1)) 
      (!! (-P- adjacent 12 2)) 
      (!! (-P- adjacent 12 3)) 
      (!! (-P- adjacent 12 4)) 
      (!! (-P- adjacent 12 5)) 
      (!! (-P- adjacent 12 6)) 
      (-P- adjacent 12 7) 
      (-P- adjacent 12 8) 
      (!! (-P- adjacent 12 9)) 
      (!! (-P- adjacent 12 10)) 
      (-P- adjacent 12 11) 
      (!! (-P- adjacent 12 12)) 
      (-P- adjacent 12 13) 
      (!! (-P- adjacent 12 14)) 
      (!! (-P- adjacent 12 15)) 
      (!! (-P- adjacent 13 1)) 
      (!! (-P- adjacent 13 2)) 
      (!! (-P- adjacent 13 3)) 
      (!! (-P- adjacent 13 4)) 
      (!! (-P- adjacent 13 5)) 
      (!! (-P- adjacent 13 6)) 
      (!! (-P- adjacent 13 7)) 
      (!! (-P- adjacent 13 8)) 
      (!! (-P- adjacent 13 9)) 
      (!! (-P- adjacent 13 10)) 
      (-P- adjacent 13 11) 
      (-P- adjacent 13 12) 
      (!! (-P- adjacent 13 13)) 
      (!! (-P- adjacent 13 14)) 
      (!! (-P- adjacent 13 15)) 
      (-P- adjacent 14 1) 
      (-P- adjacent 14 2) 
      (!! (-P- adjacent 14 3)) 
      (!! (-P- adjacent 14 4)) 
      (!! (-P- adjacent 14 5)) 
      (!! (-P- adjacent 14 6)) 
      (!! (-P- adjacent 14 7)) 
      (!! (-P- adjacent 14 8)) 
      (!! (-P- adjacent 14 9)) 
      (!! (-P- adjacent 14 10)) 
      (!! (-P- adjacent 14 11)) 
      (!! (-P- adjacent 14 12)) 
      (!! (-P- adjacent 14 13)) 
      (!! (-P- adjacent 14 14)) 
      (!! (-P- adjacent 14 15)) 
      (!! (-P- adjacent 15 1)) 
      (!! (-P- adjacent 15 2)) 
      (-P- adjacent 15 3) 
      (-P- adjacent 15 4) 
      (!! (-P- adjacent 15 5)) 
      (!! (-P- adjacent 15 6)) 
      (!! (-P- adjacent 15 7)) 
      (!! (-P- adjacent 15 8)) 
      (!! (-P- adjacent 15 9)) 
      (!! (-P- adjacent 15 10)) 
      (!! (-P- adjacent 15 11)) 
      (!! (-P- adjacent 15 12)) 
      (!! (-P- adjacent 15 13)) 
      (!! (-P- adjacent 15 14)) 
      (!! (-P- adjacent 15 15)))))

(define-var adjacent *int* *int* *bool*)

(defconstant adjacent-anti-reflexive
  (alw (-A- x areas
            (!! (-P- adjacent x x)))))

(defconstant adjacent-symmetric
  (alw (-A- x areas
            (-A- y areas (<-> (-P- adjacent x y)
                              (-P- adjacent y x))))))

(defconstant grid-adjacency-properties
  (&& adjacent-anti-reflexive
      adjacent-symmetric))

(define-var danger *int* *bool*)

(defconstant grid-danger-areas
  (alw (-A- x areas (<-> (-P- danger x)
                         (|| ([=] x 1)
                          ([=] x 2)
                          ([=] x 3)
                          ([=] x 4)
                          ([=] x 5)
                          ([=] x 8)
                          ([=] x 9)
                          ([=] x 10)
                          ([=] x 11)
                          ([=] x 12)
                          ([=] x 13)
                          ([=] x 14)
                          ([=] x 15))))))

(defun are-adjacent (x y)
  (-P- adjacent x y))

(defconstant grid-axioms
  (&& grid-adjacency
      grid-danger-areas))